version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0
workflows:
  version: 2
  commit:
    jobs:
      - raspi-image-create
      - virtualbox-image-create
      - s3-sync:
          requires:
            - raspi-image-create
            - virtualbox-image-create

  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - raspi-image-create
      - virtualbox-image-create

jobs:
  raspi-image-create:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: sudo apt-get update && sudo apt-get -y install pigz dosfstools gcc-aarch64-linux-gnu git kpartx live-build sudo wget
      - run:
          name: Create base SD card image for Raspberry Pi
          command: >-
            CIRCLE_BRANCH_ESC=$(echo "$CIRCLE_BRANCH" | tr '/' '_')
            mkdir /tmp/images &&
            ROOTFS_BUILD_TAG="$(git describe --tags HEAD | sed 's/_/~/' | sed 's/-/+/g')" &&          
            sudo scripts/create_raspi_base_image.sh --dest /tmp/images/jaiabot_"$CIRCLE_BRANCH_ESC"_img-"$ROOTFS_BUILD_TAG".img --native
      - run:
          name: Compress image
          command: pigz /tmp/images/*.img
      - store_artifacts:
          path: /tmp/images/
      - persist_to_workspace:
          root: /tmp
          paths:
            - 'images/*.img.gz'
            
  virtualbox-image-create:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: sudo apt-get update && sudo apt-get -y install dosfstools gcc-aarch64-linux-gnu git kpartx live-build sudo wget virtualbox
      - run:
          name: Create base SD card image for VirtualBox
          command: >-
            CIRCLE_BRANCH_ESC=$(echo "$CIRCLE_BRANCH" | tr '/' '_')
            mkdir /tmp/images &&
            ROOTFS_BUILD_TAG="$(git describe --tags HEAD | sed 's/_/~/' | sed 's/-/+/g')" &&          
            sudo scripts/create_raspi_base_image.sh --dest /tmp/images/jaiabot_"$CIRCLE_BRANCH_ESC"_img-"$ROOTFS_BUILD_TAG".img --virtualbox
      - run:
          name: Move image for storage
          command: >-
            mkdir /tmp/vbox &&
            sudo chmod a+rwx /tmp/images/*.ova &&
            mv /tmp/images/*.ova /tmp/vbox/
      - store_artifacts:
          path: /tmp/vbox/
      - persist_to_workspace:
          root: /tmp
          paths:
            - 'vbox/*.ova'
  
  s3-sync:
    docker:
      - image: cimg/base:current
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp
      - aws-cli/setup:
          profile_name: OIDC-User
          role_arn: arn:aws:iam::472532551733:role/JaiaS3JaiaBotImagesCircleCI
      - aws-s3/sync:
          profile_name: OIDC-User
          from: /tmp/vbox
          to: s3://jaiabot-images-test/vbox
      - aws-s3/sync:
          profile_name: OIDC-User
          from: /tmp/images
          to: s3://jaiabot-images-test/rpi

          