version: 2
workflows:
  version: 2
  commit:
    jobs:
      - raspi-image-create      
      - virtualbox-image-create
  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - raspi-image-create
      - virtualbox-image-create

jobs:
  raspi-image-create:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: sudo apt-get update && sudo apt-get -y install pigz dosfstools gcc-aarch64-linux-gnu git kpartx live-build sudo wget
      - run:
          name: Create base SD card image for Raspberry Pi
          command: >-
            mkdir images &&
            sudo scripts/create_raspi_base_image.sh --dest images/base_image.img --native
      - run:
          name: Rename image
          command: >-
            CIRCLE_BRANCH_ESC=$(echo "$CIRCLE_BRANCH" | tr '/' '_')
            ROOTFS_BUILD_TAG="$(git describe --tags HEAD | sed 's/_/~/' | sed 's/-/+/g')" &&          
            mv images/base_image.img \
               images/jaiabot_"$CIRCLE_BRANCH_ESC"_img-"$ROOTFS_BUILD_TAG".img
      - run:
          name: Compress image
          command: pigz images/*.img
      - store_artifacts:
          path: images/
  virtualbox-image-create:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: sudo apt-get update && sudo apt-get -y install pigz dosfstools gcc-aarch64-linux-gnu git kpartx live-build sudo wget virtualbox
      - run:
          name: Create base SD card image for VirtualBox
          command: >-
            CIRCLE_BRANCH_ESC=$(echo "$CIRCLE_BRANCH" | tr '/' '_')
            mkdir images &&
            ROOTFS_BUILD_TAG="$(git describe --tags HEAD | sed 's/_/~/' | sed 's/-/+/g')" &&          
            sudo scripts/create_raspi_base_image.sh --dest images/jaiabot_"$CIRCLE_BRANCH_ESC"_img-"$ROOTFS_BUILD_TAG".img --virtualbox
      - run:
          name: Move image for storage
          command: >-
            mkdir vbox &&
            sudo chmod a+rwx images/*.ova &&
            mv images/*.ova vbox/
      - store_artifacts:
          path: vbox/
